HED_MODEL_URL = 'http://vcl.ucsd.edu/hed/hed_pretrained_bsds.caffemodel'
HED_MODEL_DIR = 'utils/hed_model'
HED_MODEL_FILENAME = 'hed_pretrained_bsds.caffemodel'
HED_MODEL_FILEPATH = f'{HED_MODEL_DIR}/{HED_MODEL_FILENAME}'
HED_MODEL_PROTOTXT_FILEPATH = f'{HED_MODEL_DIR}/deploy.prototxt'

IMG_HEIGHT = 256
IMG_WIDTH = 256
IMG_N_CHANNELS = 3
IMG_SHAPE = IMG_HEIGHT, IMG_WIDTH, IMG_N_CHANNELS
IMG_PATCH_HEIGHT = 16
IMG_PATCH_WIDTH = 16

USER_COLOR_POINTS_PER_IMG = 100
USER_COLOR_POINTS_CIRCLE_RADIUS = 3

ZAPPOS_DATASET_URL = 'http://vision.cs.utexas.edu/projects/finegrained/utzap50k/ut-zap50k-images-square.zip'
ZAPPOS_DATASET_NAME = 'ut-zap50k-images-square'
ZAPPOS_DATASET_SNEAKERS_DIR = f'{ZAPPOS_DATASET_NAME}/Shoes/Sneakers and Athletic Shoes'
ZAPPOS_DATASET_MIN_SHOE_MODEL_ID_COUNT = 3

TRAINING_DIR = 'data/training'
TRAINING_SOURCE_DIR = f'{TRAINING_DIR}/source'
TRAINING_TARGET_DIR = f'{TRAINING_DIR}/target'
TRAINING_BATCH_SIZE = 1

VALIDATION_DIR = 'data/validation'
VALIDATION_SOURCE_DIR = f'{VALIDATION_DIR}/source'
VALIDATION_TARGET_DIR = f'{VALIDATION_DIR}/target'
VALIDATION_BATCH_SIZE = 9
